AWSTemplateFormatVersion: 2010-09-09
Description: "Deploy aws weather app using AWS Cloudformation"

Parameters:
  Environment:
    Type: String
    Description: Environment Name

  ElementName:
    Type: String
    Default: cityId
    Description: City Id

  ElementType:
    Type: String
    Default: N
    Description: Type

  StageName:
    Type: String
    Default: dev

Resources:
  
  iamAwsWeatherAppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: "aws-weather-app-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:TagResource'
                  - 'dynamodb:UntagResource'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                Resource: '*'
              - Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  
  AwsWeatherAppDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref ElementName
          AttributeType: !Ref ElementType
      KeySchema:
        - AttributeName: !Ref ElementName
          KeyType: HASH
      TableName: WeatherDetail
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DependsOn:
      - iamAwsWeatherAppRole

  awsWeatherAppLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Deploy Springboot app to Lambda function"
      FunctionName: !Sub aws-weather-map-${Environment}-function
      Handler: com.casestudy.a61098390.awsWeatherApiCasestudy.StreamLambdaHandler::handleRequest
      MemorySize: 128
      Role: !GetAtt iamAwsWeatherAppRole.Arn
      Runtime: java17
      Timeout: 100
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: aws-weather-app-bucket
        S3Key: awsWeatherApiCasestudy-lambda-package.zip
      Tags:
        - Key: keyname
          Value: value
    DependsOn:
      - AwsWeatherAppDynamoTable
  
  awsWeatherAppRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: A Rest API to integrate with Lambda function
      Name: aws-weather-app-rest-api
    DependsOn:
      - awsWeatherAppLambdaFunction

  awsWeatherAppRestApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref awsWeatherAppRestApi
      ParentId: !GetAtt
        - awsWeatherAppRestApi
        - RootResourceId
      PathPart: '{proxy+}'
    DependsOn:
      - awsWeatherAppRestApi
  
  awsWeatherAppRestApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref awsWeatherAppRestApi
      ResourceId: !Ref awsWeatherAppRestApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: ANY
        Uri: !Sub
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !GetAtt awsWeatherAppLambdaFunction.Arn
    DependsOn:
      - awsWeatherAppRestApiResource
  
  awsWeatherAppRestApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref awsWeatherAppRestApi
      StageName: !Ref StageName
    DependsOn:
      - awsWeatherAppRestApiMethod

  awsWeatherAppPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt awsWeatherAppLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - awsWeatherAppRestApiDeployment


Outputs:
  awsWeatherAppLambdaFunction:
    Description: "Lambda funciton created"
    Value: !Ref awsWeatherAppLambdaFunction
  AwsWeatherAppDynamoTable:
    Description: "Employee Dynamo DB created"
    Value: !Ref AwsWeatherAppDynamoTable