Resources:
  WeatherDynamoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: WeatherDetail
      AttributeDefinitions:
        - AttributeName: cityId
          AttributeType: N
      KeySchema:
        - AttributeName: cityId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  WeatherIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  WeatherIamPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:ConditionCheckItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:GetItem'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
              - 'dynamodb:PutItem'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:UpdateItem'
            Effect: Allow
            Resource:
              - !GetAtt 
                - WeatherDynamoTable
                - Arn
              - !Ref 'AWS::NoValue'
        Version: 2012-10-17
      PolicyName: WeatherIamPolicy
      Roles:
        - !Ref WeatherIamRole

  WeatherLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: aws-weather-app-bucket
        S3Key: awsWeatherApiCasestudy-lambda-package.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref WeatherDynamoTable
      Handler: com.casestudy.a61098390.awsWeatherApiCasestudy.StreamLambdaHandler::handleRequest
      MemorySize: 1024
      Role: !GetAtt 
        - WeatherIamRole
        - Arn
      Runtime: java17
      Timeout: 30
    DependsOn:
      - WeatherIamPolicy
      - WeatherIamRole

  WeatherLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17

  WeatherLambdaRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'dynamodb:DeleteItem'
              - 'dynamodb:GetItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:UpdateItem'
            Effect: Allow
            Resource: !GetAtt 
              - WeatherDynamoTable
              - Arn
        Version: 2012-10-17
      PolicyName: WeatherLambdaRolePolicy
      Roles:
        - !Ref WeatherLambdaRole

  WeatherRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: This service serves weather data.
      Name: Weather-app-rest-api

  WeatherApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt 
        - WeatherRestApi
        - RootResourceId
      PathPart: '/{proxy+}'
      RestApiId: !Ref WeatherRestApi

  WeatherApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: ANY
        Type: PROXY
        Uri: !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - WeatherLambdaFunction
              - Arn
            - /invocations
      ResourceId: !Ref WeatherApiResource
      RestApiId: !Ref WeatherRestApi

  WeatherApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description: This service serves weather data.
      RestApiId: !Ref WeatherRestApi
    DependsOn:
      - WeatherApiMethod
      - WeatherApiResource

  WeatherApiDeploymentStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref WeatherApiDeployment
      RestApiId: !Ref WeatherRestApi
      StageName: prod

  WeatherApiLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - WeatherLambdaFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref WeatherRestApi
          - /
          - !Ref WeatherApiDeploymentStage

  WeatherEventBus:
    Type: 'AWS::Events::EventBus'
    Properties:
      Name: WeatherEventBus

  WeatherEventBridgeRule:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt 
            - WeatherLambdaFunction
            - Arn
          Id: Target0

  WeatherEventRulePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 
        - WeatherLambdaFunction
        - Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 
        - WeatherEventBridgeRule
        - Arn

Outputs:
  WeatherApiEndpoint9062F38A:
    Value: !Join 
      - ''
      - - 'https://'
        - !Ref WeatherRestApi
        - .execute-api.
        - !Ref 'AWS::Region'
        - .
        - !Ref 'AWS::URLSuffix'
        - /
        - !Ref WeatherApiDeploymentStage
        - /
